ocfs2-tools: more verbose init script

diff --git a/trunk/sys-fs/ocfs2-tools/files/ocfs2.init b/trunk/sys-fs/ocfs2-tools/files/ocfs2.init
--- a/trunk/sys-fs/ocfs2-tools/files/ocfs2.init
+++ b/trunk/sys-fs/ocfs2-tools/files/ocfs2.init
@@ -12,30 +12,38 @@ depend() {
 
 pseudofs() {
 	[ -n "`mount -l -t $1`" ] && return 0
-	ewarn "Pseudo-filesystem $1 are not mounted."
+	ewarn "OCFS2: Pseudo-filesystem $1 are not mounted."
 	ewarn "Make sure you have following lines in your /etc/fstab:"
 	ewarn "none         $2         $1        defaults                0 0"
 
 	# Why not?
 	ebegin "Mounting $1"
-	if mount -t $1 none $2 && [ -n "`mount -l -t $1`" ] ; then
-		eend 0
-		return 0
-	fi
-	eend 1
+	mount -t $1 none $2 && [ -n "`mount -l -t $1`" ]
+	eend $? || return 1
+}
+
+fmod() {
+	[[ -e "$1" ]] && return 0
+	modprobe -s $2 && [[ -e "$1" ]] &&  return 0
+	eerror "OCFS2: Module '$2' failed, '$1' not found"
 	return 1
 }
 
 start() {
-	# Modules will be loaded on mount, no other checks.
-	# Unless other modules will be failed to configure.
-	pseudofs configfs /sys/kernel/config || return 1
-	pseudofs ocfs2_dlmfs /dlm || return 1
+	(	fmod /sys/fs/ocfs2 ocfs2 &&
+		fmod /sys/fs/ocfs2/cluster_stack ocfs2_stackglue &&
+		pseudofs configfs /sys/kernel/config &&
+		pseudofs ocfs2_dlmfs /dlm
+	) || return 1
+	echo o2cb >/sys/fs/ocfs2/cluster_stack 2>/dev/null
+	if [[ "`cat /sys/fs/ocfs2/cluster_stack`" != "o2cb" ]]; then
+		eerror "OCFS2: Stack 'o2cb' not loaded. Check your kernel config."
+		return 1
+	fi
 
-	einfo "Starting OCFS2 cluster"
 	for cluster in ${OCFS2_CLUSTER}; do
-		ebegin " - ${cluster}"
-		/sbin/o2cb_ctl -H -n ${cluster} -t cluster -a online=yes >/dev/null 2>&1
+		ebegin "Starting OCFS2 cluster '${cluster}'"
+		/sbin/o2cb_ctl -H -n ${cluster} -t cluster -a online=yes
 		eend $? || return 1
 
 		# Some heartbeat tweaks to prevent self-fencing quite so much during heavy load.
@@ -57,7 +65,7 @@ start() {
 	local i
 	for i in `mount -invfat ocfs2 2>/dev/null|sed -e 's: .*::g'` ; do
 		[[ -e "$i" ]] || continue
-		einfo "Trying 'fsck.ocfs2 $OCFS2_FSCK $i'"
+		einfo "OCFS2: Trying 'fsck.ocfs2 $OCFS2_FSCK $i' (fs check if possible)"
 		fsck.ocfs2 $OCFS2_FSCK "$i" 2>/dev/null
 	done
 
@@ -98,7 +106,7 @@ stop() {
 	einfo "Stopping OCFS2 cluster" 
 	for cluster in ${OCFS_CLUSTERS}; do
 		ebegin " - ${cluster}"
-		/sbin/o2cb_ctl -H -n ${cluster} -t cluster -a online=no >/dev/null 2>&1
+		/sbin/o2cb_ctl -H -n ${cluster} -t cluster -a online=no
 		eend $?
 	done
 }
