ya-nrg: remove slow mode as "fast" looks secure now

diff --git a/x11-misc/ya-layout/files/usr/sbin/ya-nrg b/x11-misc/ya-layout/files/usr/sbin/ya-nrg
--- a/x11-misc/ya-layout/files/usr/sbin/ya-nrg
+++ b/x11-misc/ya-layout/files/usr/sbin/ya-nrg
@@ -40,18 +40,18 @@ save1(){
 		read x <$f &&
 		x=${x#*'['} &&
 		x=${x%%']'*} &&
-		echo "$f $x" >>$save &&
-		$echo "$x -> $y => $f" &&
 		[ "$x" != "$y" ] &&
-		echo "$y" >$f
-	done
+		echo "$y" >$f &&
+		$echo "$x -> $y => $f" &&
+		echo "echo $x >$f"
+	done >>$save
 	return 0
 }
 
 fchk(){
 	local s
 	s="$(stat $1 -c '%u:%g:%f')" || {
-		touch $1 && s="$(stat $1 -c '%u:%g:%f')" || die "file '$1' insecure! check & remove"
+		touch $1 && s="$(stat $1 -c '%u:%g:%f')" || die "file '$1' create error"
 	}
 	[ "$s" = 0:0:8180 ] || die "file '$1' insecure! check & remove"
 	[ -s $1 ]
@@ -71,31 +71,10 @@ restore(){
 	flock -s 3
 	local f x i s b=false
 	for s in ${save}1 $save; do
-	    fchk $s || continue
-	    if $fast; then
+		fchk $s || continue
 		(. $s)
-	    else
-	      while read f x; do
-		case "$f" in
-		/sys/*)
-#			f=$(readlink -f "$f") && [[ "$f" == /sys/* ]] || continue # paranoid
-			$echo "restore $x -> $f"
-			echo "$x" >"$f"
-		;;
-		x86_energy_perf_policy)
-			$echo "$f $x"
-			($f $x)
-		;;
-		exit);;
-		echo)die "fast mode restore file in secure run";;
-		*)die "invalid file '$s' command '$f'";;
-		esac
-	      done <$s
-	    fi
-	    [ "$s" = ${save}1 ] && b=true && jiff
-	    true >$s
+		true >$s
 	done
-	$b && balance
     } 3>>$save.lock
 }
 
@@ -105,7 +84,6 @@ save(){
 	flock 3
 	fchk $save && return
 	local f i x x1
-	$fast || echo exit >>$save
 	save1 min_power /sys/class/scsi_host/*/link_power_management_policy
 	save1 powersupersave /sys/module/pcie_aspm/parameters/policy
 	# must be ordered
@@ -140,18 +118,19 @@ save(){
 		$f 15
 	}
 	[ -n "$cores" ] && [ "$[cores-1]" -lt "$cores" -a "$cores" -ge 0 ] && {
+	    echo balance >>$save
 	    save+=1
-	    fchk $save
 	    sync &
 	    i=$!
+	    fchk $save
 	    jiff
 	    wait $i
-	    $fast || echo exit >>$save
 	    for i in /sys/devices/system/cpu/cpu*/online; do
 		[ -e "$i" ] || break
 		[ "$cores" -gt 0 ] || save1 0 "$i"
 		cores=$[cores-1]
 	    done
+	    echo jiff >>$save
 	    # single CPU must be balanced. fixme
 	    #balance
 	}
@@ -162,16 +141,17 @@ save(){
 umask 077
 
 echo=true
-echo1=echo
 cores=
 light=
 pw=
-fast=false
 
 while [ -n "$*" ]; do
 case "$1" in
 light|cores)declare $1="$2";shift;;
-verbose)echo=echo;;
+verbose)
+	_echo(){ echo "${@}" >&2;}
+	echo=_echo
+;;
 xss|xss-auto)
 	shift
 	case "$1" in
@@ -194,23 +174,6 @@ auto|bat|batt|xss-auto)
 ;;&
 bat|batt)pw=$batt;;
 auto|xss-auto)$batt && pw=save || pw=restore;;
-fast)
-    fast=true
-    save1(){
-	[ -e "$2" ] || return 1
-	local f y=$1 x=
-	shift
-	for f in "${@}"; do
-		read x <$f &&
-		x=${x#*'['} &&
-		x=${x%%']'*} &&
-		[ "$x" != "$y" ] &&
-		echo "$y" >$f &&
-		echo "echo $x >$f"
-	done >>$save
-	return 0
-    }
-;;
 *)
 echo "Simple control powersave <-> default & check battery state.
 Designed for use in parallel with screen locker on laptop.
@@ -219,7 +182,6 @@ opt is:
  light <brightness_percent>
  cores <num>
  verbose
- fast
 cmd is:
  powersave|save|power|low
  performance|perf|restore|high
